# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'nv200_controller_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QDoubleSpinBox,
    QFrame, QSizePolicy, QSpinBox, QWidget)
import pysoworks_rc

class Ui_nv200ControllerWidget(object):
    def setupUi(self, nv200ControllerWidget):
        if not nv200ControllerWidget.objectName():
            nv200ControllerWidget.setObjectName(u"nv200ControllerWidget")
        nv200ControllerWidget.resize(1376, 850)
        nv200ControllerWidget.setAutoFillBackground(False)
        nv200ControllerWidget.setStyleSheet(u"#nv200ControllerWidget{\n"
"background-image: url(:/assets/images/nv200_controller_structure.png);\n"
"background-repeat: no-repeat;}\n"
"")
        self.doubleSpinBox_3 = QDoubleSpinBox(nv200ControllerWidget)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        self.doubleSpinBox_3.setGeometry(QRect(239, 174, 75, 24))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.doubleSpinBox_3.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox_3.setDecimals(3)
        self.spinBox = QSpinBox(nv200ControllerWidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(347, 190, 94, 24))
        self.spinBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.checkBox_2 = QCheckBox(nv200ControllerWidget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(807, 160, 96, 20))
        self.checkBox_2.setProperty(u"toggleSwitch", True)
        self.spinBox_3 = QSpinBox(nv200ControllerWidget)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(807, 217, 118, 24))
        self.spinBox_3.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_2 = QSpinBox(nv200ControllerWidget)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(807, 187, 118, 24))
        self.spinBox_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.iEdit = QDoubleSpinBox(nv200ControllerWidget)
        self.iEdit.setObjectName(u"iEdit")
        self.iEdit.setGeometry(QRect(522, 175, 120, 24))
        sizePolicy.setHeightForWidth(self.iEdit.sizePolicy().hasHeightForWidth())
        self.iEdit.setSizePolicy(sizePolicy)
        self.iEdit.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.iEdit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.iEdit.setDecimals(3)
        self.pcfsEdit = QDoubleSpinBox(nv200ControllerWidget)
        self.pcfsEdit.setObjectName(u"pcfsEdit")
        self.pcfsEdit.setGeometry(QRect(509, 86, 135, 24))
        sizePolicy.setHeightForWidth(self.pcfsEdit.sizePolicy().hasHeightForWidth())
        self.pcfsEdit.setSizePolicy(sizePolicy)
        self.pcfsEdit.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.pcfsEdit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.pcfsEdit.setDecimals(6)
        self.checkBox = QCheckBox(nv200ControllerWidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(347, 161, 96, 20))
        self.checkBox.setProperty(u"toggleSwitch", True)
        self.doubleSpinBox = QDoubleSpinBox(nv200ControllerWidget)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(87, 55, 104, 24))
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.doubleSpinBox.setReadOnly(True)
        self.doubleSpinBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox.setSpecialValueText(u"setst")
        self.doubleSpinBox.setDecimals(3)
        self.pcfvEdit = QDoubleSpinBox(nv200ControllerWidget)
        self.pcfvEdit.setObjectName(u"pcfvEdit")
        self.pcfvEdit.setGeometry(QRect(509, 50, 135, 24))
        sizePolicy.setHeightForWidth(self.pcfvEdit.sizePolicy().hasHeightForWidth())
        self.pcfvEdit.setSizePolicy(sizePolicy)
        self.pcfvEdit.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.pcfvEdit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.pcfvEdit.setDecimals(6)
        self.dEdit = QDoubleSpinBox(nv200ControllerWidget)
        self.dEdit.setObjectName(u"dEdit")
        self.dEdit.setGeometry(QRect(522, 205, 120, 24))
        sizePolicy.setHeightForWidth(self.dEdit.sizePolicy().hasHeightForWidth())
        self.dEdit.setSizePolicy(sizePolicy)
        self.dEdit.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.dEdit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dEdit.setDecimals(3)
        self.pEdit_2 = QDoubleSpinBox(nv200ControllerWidget)
        self.pEdit_2.setObjectName(u"pEdit_2")
        self.pEdit_2.setGeometry(QRect(237, 343, 110, 24))
        sizePolicy.setHeightForWidth(self.pEdit_2.sizePolicy().hasHeightForWidth())
        self.pEdit_2.setSizePolicy(sizePolicy)
        self.pEdit_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.pEdit_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.pEdit_2.setDecimals(3)
        self.pcfaEdit = QDoubleSpinBox(nv200ControllerWidget)
        self.pcfaEdit.setObjectName(u"pcfaEdit")
        self.pcfaEdit.setGeometry(QRect(509, 24, 135, 24))
        sizePolicy.setHeightForWidth(self.pcfaEdit.sizePolicy().hasHeightForWidth())
        self.pcfaEdit.setSizePolicy(sizePolicy)
        self.pcfaEdit.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.pcfaEdit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.pcfaEdit.setDecimals(6)
        self.pEdit = QDoubleSpinBox(nv200ControllerWidget)
        self.pEdit.setObjectName(u"pEdit")
        self.pEdit.setGeometry(QRect(522, 145, 120, 24))
        sizePolicy.setHeightForWidth(self.pEdit.sizePolicy().hasHeightForWidth())
        self.pEdit.setSizePolicy(sizePolicy)
        self.pEdit.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.pEdit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.pEdit.setDecimals(3)
        self.doubleSpinBox_2 = QDoubleSpinBox(nv200ControllerWidget)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(87, 86, 104, 24))
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.doubleSpinBox_2.setReadOnly(True)
        self.doubleSpinBox_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox_2.setDecimals(3)
        self.checkBox_3 = QCheckBox(nv200ControllerWidget)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(237, 316, 105, 20))
        self.checkBox_3.setProperty(u"toggleSwitch", True)

        self.retranslateUi(nv200ControllerWidget)

        QMetaObject.connectSlotsByName(nv200ControllerWidget)
    # setupUi

    def retranslateUi(self, nv200ControllerWidget):
        nv200ControllerWidget.setWindowTitle(QCoreApplication.translate("nv200ControllerWidget", u"Frame", None))
        self.doubleSpinBox_3.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"sr   ", None))
        self.spinBox.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"setlpf   ", None))
        self.checkBox_2.setText(QCoreApplication.translate("nv200ControllerWidget", u"notchon", None))
        self.spinBox_3.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"notchb   ", None))
        self.spinBox_2.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"notchf   ", None))
        self.iEdit.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"I   ", None))
        self.pcfsEdit.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"pcf_s   ", None))
        self.checkBox.setText(QCoreApplication.translate("nv200ControllerWidget", u"setlpon", None))
        self.doubleSpinBox.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"setst   ", None))
        self.pcfvEdit.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"pcv_v   ", None))
        self.dEdit.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"D  ", None))
        self.pEdit_2.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"poslpf   ", None))
        self.pcfaEdit.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"pcf_a   ", None))
        self.pEdit.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"P   ", None))
        self.doubleSpinBox_2.setSpecialValueText(QCoreApplication.translate("nv200ControllerWidget", u"set", None))
        self.doubleSpinBox_2.setPrefix(QCoreApplication.translate("nv200ControllerWidget", u"set   ", None))
        self.checkBox_3.setText(QCoreApplication.translate("nv200ControllerWidget", u"poslpon", None))
    # retranslateUi

