name: Build Windows Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]  # Run this when a release is published
  workflow_dispatch:

permissions:
  contents: write  # Required to upload to releases
  actions: read    # Required for artifact sharing across jobs

jobs:
  build-exe:
    name: Build Windows Executable
    runs-on: windows-latest

    outputs:
      artifact-name: PySoWorks.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.2'

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          poetry install --no-interaction --with dev

      - name: Install PyInstaller
        run: |
          poetry run pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          poetry run pyinstaller --clean --log-level=DEBUG pysoworks.spec

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PySoWorks.exe
          path: dist/PySoWorks.exe

      - name: Upload to GitHub Release (if applicable)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/PySoWorks.exe
          name: PySoWorks-${{ github.ref_name }}.exe


  build-installer:
    name: Build Installer with Inno Setup
    runs-on: windows-latest
    needs: build-exe  # <-- makes this job wait until exe is built

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executable artifact
        uses: actions/download-artifact@v4
        with:
          name: PySoWorks.exe
          path: dist

      - name: Compile Inno Setup Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: pysoworks_inno_setup.iss

      - name: Upload Installer as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PySoWorks_Setup.exe
          path: dist/PySoWorks_Setup.exe

      - name: Upload to GitHub Release (if applicable)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/PySoWorks_Setup.exe