name: Build Windows Installer

on:
  workflow_run:
    workflows: ["Build Windows Executable"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build the Inno Setup Installer
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executable artifact from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: PySoWorks.exe
          path: dist  # Make sure this matches expected location in your .iss script

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: pysoworks_inno_setup.iss

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: PySoWorks_Setup.exe
          path: dist/PySoWorks_Setup.exe 